### ISSUE TITLE
Getting a sprite dynamically in a loop

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Phunky/vue-svg-directive#1]
Hi there!

I'm massively using your little script, but for a specific task I need to load different sprites in a v-for loop.

Example:

``` vue
<div class="foo" v-for="post in posts">
    <svg v-svg sprite="{{ post.image }}"></svg>
</div>
```

Obviously, it’s not working. It output an error ("invalid character error"). I can’t find a way to get this done properly…

Thanks in advance for any hint.

**Comment by EmmanuelBeziat** [comment]
(Note i have this working if I use a normal html svg syntax, but i'd like to stick with your svg directive)

**Comment by Phunky** [comment]
Sorry for the late response, didn't get a notification for this... must have them disabled!

Believe you want to be binding the sprite value `<svg v-svg :sprite="post.image"></svg>`

**Comment by EmmanuelBeziat** [comment]
Simple and clean.

I don't get all the magic of Vue so far, need to work on it.

Thanks!
